/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlidesRouteImport } from './routes/slides'
import { Route as ProductRouteImport } from './routes/product'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as DomainRouteImport } from './routes/domain'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SlidesRoute = SlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainRoute = DomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/domain': typeof DomainRoute
  '/milestones': typeof MilestonesRoute
  '/product': typeof ProductRoute
  '/slides': typeof SlidesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/domain': typeof DomainRoute
  '/milestones': typeof MilestonesRoute
  '/product': typeof ProductRoute
  '/slides': typeof SlidesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/domain': typeof DomainRoute
  '/milestones': typeof MilestonesRoute
  '/product': typeof ProductRoute
  '/slides': typeof SlidesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/documents'
    | '/domain'
    | '/milestones'
    | '/product'
    | '/slides'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/documents'
    | '/domain'
    | '/milestones'
    | '/product'
    | '/slides'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/documents'
    | '/domain'
    | '/milestones'
    | '/product'
    | '/slides'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRoute
  DomainRoute: typeof DomainRoute
  MilestonesRoute: typeof MilestonesRoute
  ProductRoute: typeof ProductRoute
  SlidesRoute: typeof SlidesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/slides': {
      id: '/slides'
      path: '/slides'
      fullPath: '/slides'
      preLoaderRoute: typeof SlidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain': {
      id: '/domain'
      path: '/domain'
      fullPath: '/domain'
      preLoaderRoute: typeof DomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRoute,
  DomainRoute: DomainRoute,
  MilestonesRoute: MilestonesRoute,
  ProductRoute: ProductRoute,
  SlidesRoute: SlidesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
